name: tungleua
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  dio: ^5.2.0+1
  dotted_border: ^2.0.0+3
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_map: ^5.0.0
  image_picker: ^0.8.8
  latlong2: ^0.9.0
  location: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
